config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :users do
    collection do
      post :import
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/generate_csv.rb
module GenerateCsv extend ActiveSupport::Concern
  require 'csv'
  class_methods do
    def to_csv(collection)
      CSV.generate(col_sep: ";") do |csv|
        # csv << column_name
        csv << attribute_names
        collection.find_each do |record|
        csv << record.attributes.values
        end
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
    include GenerateCsv
end

app/models/user.rb
class User < ApplicationRecord
    include GenerateCsv
    
    validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  require 'csv'
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_data Order.to_csv(@orders), filename: Date.today.to_s, content_type: "text/csv"
      end
    end
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token 
  before_action :set_user, only: %i[ show edit update destroy ]
  

  # GET /users or /users.json
  def index
    @users = User.order(created_at: :desc)
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_data User.to_csv(@users), filename: Date.today.to_s, content_type: "text/csv"
      end
    end
  end

  def import
  
    file = params[:file]
    return redirect_to users_path, notice: "only csv please" unless  file.content_type == "text/csv"
    file = File.open(file)
    csv = CSV.parse(file, headers: true)
    csv.each do |row|
      user_hash = {}
      user_hash[:username] = row["Username"]
      user_hash[:identifier] = row["Identifier"]
      user_hash[:first_name] = row["First name"]
      user_hash[:last_name] = row["Last name"]
      User.create(user_hash)
      # byebug
      #  p row
    end
    redirect_to users_path, notice: 'users imported!'
  end
  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username,  :identifier, :first_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cv</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to "Download as csv", orders_path(format: :csv) %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/users/_error.html.erb
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/users/_form.html.erb
<%= form_with(model: user,local: false) do |form| %>

 <div class="modal-body">
   <div id= "errorArea" ></div>  
  <div class=form-group>
    <%= form.label :Username %>
    <%= form.text_field :username, class: 'form-control' %><br>
  </div>

  <div class=form-group>
    <%= form.label :Identifier %>
    <%= form.text_field :identifier, class: 'form-control' %><br>
  </div>

  <div class=form-group>
    <%= form.label :first_name %>
    <%= form.text_field :first_name , class: 'form-control'%><br>
  </div>


  </div>
    <%# <div class="modal-footer"> %>
    <%= form.submit class: "btn btn-primary"%>
    <button type="button" class="btn btn-secondary close-model" data-bs-dismiss="modal">Close</button>
    <%# </div> %>
<% end %>

app/views/users/_show.html.erb
<%# <p id="notice"><%= notice %>
<div class="modal-body">
<div class= "col-lg-12">
<p>
  <strong>user_name:</strong>
  <%= user.username%>
</p>

<p>
  <strong>identifier:</strong>
  <%= user.identifier %>
</p>

<p>
  <strong>first_name:</strong>
  <%= user.first_name%>
</p>
</div>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-secondary close-model" data-bs-dismiss="modal">Close</button>
</div>

app/views/users/_user_row.html.erb
  <tr id="userRow_<%= user.id %>">
        <td><%= user.username %></td>
        <td><%= user.identifier %></td>
        <td><%= user.first_name %></td>

        <td><%= link_to 'Show', user, data: { bs_toggle: 'modal', bs_target: '#showUserModal',remote: true} %></td>
        <td><%= link_to 'Edit', edit_user_path(user), data: { bs_toggle: 'modal', bs_target: '#editUserModal',remote: true} %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } ,remote: true%></td>
      </tr>

app/views/users/create.js.erb
<% if @user.errors.any? %>
$("#errorArea").html("<%= escape_javascript render('error' , user: @user)%>")
<% else %>
$("#usersTable").prepend("<%= escape_javascript render('user_row', user: @user)%>");

$(".close-model").click();

<% end %>

app/views/users/destroy.js.erb
$("#userRow_<%= @user.id %>").remove();

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.js.erb
$("#editUserForm").html("<%= escape_javascript render('form', user: @user)%>");

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "Download as csv", users_path(format: :csv), download: ["Users", Date.today] %><br><br>

<%= form_with url: import_users_path, method: :post do |form|%>
  <%= form.file_field :file,accept: ".csv" %>
  <%= form.button "import" %>
<% end %><br>

<%= link_to 'New User', new_user_path, class: "btn btn-primary  mb-4", data: {bs_toggle: 'modal', bs_target: '#newUserModal' ,remote: true} %> 

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Identifier</th>
      <th>First_name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id= "usersTable">
    <% @users.each do |user| %>
    <%= render 'user_row', user:user%>
    
    <% end %>
  </tbody>
</table>

<br>
 
<div class="modal fade" id="newUserModal" tabindex="-1" aria-labelledby="newUserModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newUserModal">Create new user</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id = "newUserForm"></div>
     
    </div>
  </div>
</div>

<div class="modal fade" id="editUserModal" tabindex="-1" aria-labelledby="editUserModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editUserModal">edit user</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id = "editUserForm"></div>
     
    </div>
  </div>
</div>

<div class="modal fade" id="showUserModal" tabindex="-1" aria-labelledby="showUserModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="showUserModal">User Details</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id = "showUserDetails"></div>
     
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/new.js.erb
$("#newUserForm").html("<%= escape_javascript render('form', user: @user)%>");

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>user_name:</strong>
  <%= @user.username%>
</p>

<p>
  <strong>identifier:</strong>
  <%= @user.identifier %>
</p>

<p>
  <strong>first_name:</strong>
  <%= @user.first_name%>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show.js.erb
$("#showUserDetails").html("<%= escape_javascript render('show' , user: @user)%>")

app/views/users/update.js.erb
<% if @user.errors.any? %>
 alert('Invalid Details');
<% else %>
$("#usersRow_<%= @user.id %>").replaceWith("<%= escape_javascript render('user_row', user: @user)%>");

$(".close-model").click();

<% end %>